baseURL: https://ok-lab-karlsruhe.de
DefaultContentLanguage: de
title: OK Lab Karlsruhe
theme: hugo-cfg
#Disables warnings
disableKinds:
 -taxonomy
 -taxonomyTerm
pluralizeListTitles: false
# tell hugo to get the date from the filename, if possible
frontmatter:
  date: [":filename", ":default"]

params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: OK Lab Karlsruhe
  navbarlogo:
   image: img/CFG_Karlsruhe.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]


languages:
  de:
    languageName: Deutsch
    weight: 1
    contentDir: content/de
    lang: de
    params:
      hero:
        # Main hero title
        title: OK Lab Karlsruhe
        # Hero subtitle (optional)
        # subtitle: Wir sind ein offenes Stadtlabor und bauen digitale Werkzeuge für alle!
        subtitle: Diese Seite ist noch im Aufbau ...
        # Button text
        buttontext: Werde Stadtentwickler*in!
        # Where the main hero button links to
        buttonlink: "mitmachen"
        # Hero image (from static/images/___)
        image: "../img/CfKA Hexagon 3d.svg" # illustrations/worker.svg
      # langiage switch: works, but keep it disabled until translation complete
      #switch:
      #  title: EN
      #  lang: Englisch
      #  code: en
      # Customizable navbar. For a dropdown, add a "sublinks" list.
      navbar:
      - title: Über uns
        url: /ueber/
      - title: Projekte
        url: /projekte/
      - title: Mitmachen
        url: /mitmachen
      - title: Code For Germany
        url: https://dev.codefor.de/
        button: false
      section1:
        title: Zivilgesellschaftliches Engagement
        subtitle: Gute Taten mit offenen Daten
        tiles:
        - # title: Design & Entwicklung
          icon: coding
          text:
          url: /
          buttonText: Entwicklung & Design
        - # title: Cloud integration
          icon: folders
          text:
          url: /
          buttonText: Politik & Verwaltung
        - # title: Add-ons & plugins
          icon: microphone
          text:
          url: /
          buttonText: Journalismus & Unterstützung
      section2:
        subtitle: Freie Software + Offene Daten = <3
        title: open source + open data = <3
        features:
        - title: Offene Daten // Open Data
          text: Offene Daten sind Daten, auf die alle Personen frei zugreifen können und die von allen genutzt, verändert und geteilt werden können. Sie werden in vielen Anwendungen erzeugt und gesammelt, beispielsweise in amtlichen Messungen oder wissenschaftlichen Experimenten.
          # Icon (from /images/illustrations/icons/___.svg)
          icon: laptop-globe
        - title: Offene Verwaltung // Open Government
          text: Politik und Verwaltung sollen geöffnet werden für Bürger*innen, Wirtschaft, Wissenschaft, Kunst und Kultur, um stärkere gemeinschaftliche Belange in einer Kommune zu ermöglichen. Im Fokus stehen dabei Transparenz, Partizipation und Kollaboration.
          icon: doc-sync
        - title: Zivilgesellschaftliche Technik // Civic Tech
          text: Technischen Konzepten können Engagement und Beteiligung von Bürgern fördern, beispielsweise durch entsprechende Kommunikationsplattformen, bessere öffentliche Infrastrukturen und technikbasierte Verbesserungen des Allgemeinwohls.
          icon: mobile-feed
      section3:
        title: Wir nehmen offene Daten
        subtitle: und bauen daraus Anwendungen für Bürger*innen.
        image: illustrations/cfg-summit-19.png
        buttonText: Zu den Projekten
        buttonLink: "/projekte/"
      section4:
        title: Unsere Schwerpunkte
        subtitle: für 2020
        clients:
        - name: Umwelt
          quote: Wir loten aus, wie viel wir für unsere Umwelt und unser Klima tun. Dazu sammeln wir offene Daten vor Ort und werten sie aus.
          job:
          img: 1
        - name: Mobilität & Infrastruktur
          quote: Im Alltag sind wir viel unterwegs. Mit offenen Daten wollen wir die sichersten Wege, die entspanntesten Verkehrsmittel und die umweltfreundlichste Fortbewegung finden.
          job:
          img: 2
        - name: Open Government
          quote: Wir sprechen mit Politiker*innen und setzen uns für Transparenz und Partizipation ein.
          job:
          img: 3
      section5: true
      footer:
        logo: /img/CFG_Karlsruhe_white.svg
        # Social Media Title
        socialmediatitle: Folge uns!
        # Social media links (GitHub, Twitter, etc.). All are optional.
        socialmedia:
        - link: https://github.com/okfde/codefor.de
          # Icons are from Font Awesome
          icon: github
        - link: https://twitter.com/codeforde
          icon: twitter
        bulmalogo: true
        quicklinks:
          column1:
            title: "Rechtliches"
            links:
            - text: Impressum
              link: /impressum/
            - text: Datenschutz
              link: /impressum/#datenschutzerklaerung
            - text: Grundsätze
              link: /grundsaetze/
          column2:
            title: "Werkzeugkoffer"
            links:
            - text: Github (extern)
              link: https://github.com/okfde
            - text: opendatahandbook.org
              link: https://opendatahandbook.org/
            - text: ABC der Offenheit
              link: https://upload.wikimedia.org/wikipedia/commons/a/a9/ABC_der_Offenheit_-_Brosch%C3%BCre_%282019%29.pdf
          column3:
            title: "Über uns"
            links:
            - text: Projekte
              link: /projekte/
            - text: Mitmachen
              link: /mitmachen/
            - text: OKF e.V.
              link: https://okfn.de/


  en:
    languageName: English
    weight: 2
    contentDir: content/en
    lang: en
    params:
      hero:
        # Main hero title
        title: OK Lab Karlsruhe
        # Hero subtitle (optional)
        # subtitle: We are a non-profit civic-tech lab working on digital tools for all
        subtitle: This site is work in progress. Stay tuned ...
        # Button text
        buttontext: Improve your city!
        # Where the main hero button links to
        buttonlink: "/en/mitmachen"
        # Hero image (from static/images/___)
        image: "../img/CfKA Hexagon 3d.svg" # illustrations/worker.svg
      # langiage switch: works, but keep it disabled until translation complete
      switch:
        title: DE
        lang: German
        code: de
      # Customizable navbar. For a dropdown, add a "sublinks" list.
      navbar:
      - title: About
        url: /en/ueber/
      - title: Projects
        url: /en/projekte/
      - title: Join us
        url: /en/mitmachen/
      - title: Code For Germany
        url: https://dev.codefor.de/
        button: false
      section1:
        title: Get Involved in Civic Tech
        subtitle: Good deeds with open data
        tiles:
        - # title: Design & Entwicklung
          icon: coding
          text:
          url: /
          buttonText: Design & Development
        - # title: Cloud integration
          icon: folders
          text:
          url: /
          buttonText: Politics & Administration
        - # title: Add-ons & plugins
          icon: microphone
          text:
          url: /
          buttonText: Journalism & Support
      section2:
        title: Open Source + Open Data = <3
        subtitle: Free Software + Open Data = <3
        features:
        - title: Offene Daten // Open Data
          text: Offene Daten sind Daten, auf die alle Personen frei zugreifen können und die von allen genutzt, verändert und geteilt werden können. Sie werden in vielen Anwendungen erzeugt und gesammelt, beispielsweise in amtlichen Messungen oder wissenschaftlichen Experimenten.
          # Icon (from /images/illustrations/icons/___.svg)
          icon: laptop-globe
        - title: Offene Verwaltung // Open Government
          text: Politik und Verwaltung sollen geöffnet werden für Bürger*innen, Wirtschaft, Wissenschaft, Kunst und Kultur, um stärkere gemeinschaftliche Belange in einer Kommune zu ermöglichen. Im Fokus stehen dabei Transparenz, Partizipation und Kollaboration.
          icon: doc-sync
        - title: Zivilgesellschaftliche Technik // Civic Tech
          text: Technischen Konzepten können Engagement und Beteiligung von Bürgern fördern, beispielsweise durch entsprechende Kommunikationsplattformen, bessere öffentliche Infrastrukturen und technikbasierte Verbesserungen des Allgemeinwohls.
          icon: mobile-feed
      section3:
        title: Wir nehmen offene Daten
        subtitle: und bauen daraus Anwendungen für Bürger*innen.
        image: illustrations/cfg-summit-19.png
        buttonText: Zu den Projekten
        buttonLink: "/projekte/"
      section4:
        title: Unsere Schwerpunkte
        subtitle: für 2020
        clients:
        - name: Umwelt
          quote: Wir loten aus, wie viel wir für unsere Umwelt und unser Klima tun. Dazu sammeln wir offene Daten vor Ort und werten sie aus.
          job:
          img: 1
        - name: Mobilität & Infrastruktur
          quote: Im Alltag sind wir viel unterwegs. Mit offenen Daten wollen wir die sichersten Wege, die entspanntesten Verkehrsmittel und die umweltfreundlichste Fortbewegung finden.
          job:
          img: 2
        - name: Open Government
          quote: Wir sprechen mit Politiker*innen und setzen uns für Transparenz und Partizipation ein.
          job:
          img: 3
      section5: true
      footer:
        logo: /img/CFG_Karlsruhe_white.svg
        # Social Media Title
        socialmediatitle: Follow us!
        # Social media links (GitHub, Twitter, etc.). All are optional.
        socialmedia:
        - link: https://github.com/okfde/codefor.de
          # Icons are from Font Awesome
          icon: github
        - link: https://twitter.com/codeforde
          icon: twitter
        bulmalogo: true
        quicklinks:
          column1:
            title: "Legal stuff"
            links:
            - text: Imprint
              link: /en/impressum/
            - text: Data protection
              link: /en/impressum/#datenschutzerklaerung
            - text: Principles
              link: /en/grundsaetze/
          column2:
            title: "Toolset"
            links:
            - text: Github (extern)
              link: https://github.com/okfde
            - text: opendatahandbook.org
              link: https://opendatahandbook.org/
            - text: ABC der Offenheit
              link: https://upload.wikimedia.org/wikipedia/commons/a/a9/ABC_der_Offenheit_-_Brosch%C3%BCre_%282019%29.pdf
          column3:
            title: "About"
            links:
            - text: Projects
              link: /en/projekte/
            - text: Join Us
              link: /en/mitmachen/
            - text: OKF e.V.
              link: https://okfn.de/


